'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ColorUtility.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property copy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property huegradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("huegradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #author=Xylem Studios
        '''#name=English
        '''#shortname=en
        '''#contact=webmaster@xylemstudios.com
        '''#site=http://xylemstudios.com
        '''
        '''RGB=RGB
        '''RGB:R=R
        '''RGB:G=G
        '''RGB:B=B
        '''
        '''HSV=HSV
        '''HSV:H=H
        '''HSV:S=S
        '''HSV:V=V
        '''
        '''FILTERS=Filters
        '''FILTERS:GRAYSCALE=Grayscale
        '''FILTERS:NEGATIVE=Negative
        '''FILTERS:SEPIA=Sepia
        '''FILTERS:BRIGHTER=Brighter
        '''FILTERS:DARKER=Darker
        '''FILTERS:INTENSIFY=Intensify
        '''FILTERS:REDONLY=Red only
        '''FILTERS:GREENONLY=Green only
        '''FILTERS:BLUEONLY=Blue only
        '''FILTERS:RGBSHUFFLE=RGB Shuffle
        '''FILTERS:HOVER=Hover over [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_English() As String
            Get
                Return ResourceManager.GetString("lang_English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #author=Xylem Studios
        '''#name=Français
        '''#shortname=fr
        '''#contact=webmaster@xylemstudios.com
        '''#site=http://xylemstudios.com
        '''
        '''RGB=RVB
        '''RGB:R=R
        '''RGB:G=V
        '''RGB:B=B
        '''
        '''HSV=TSV
        '''HSV:H=T
        '''HSV:S=S
        '''HSV:V=V
        '''
        '''FILTERS=Filtres
        '''FILTERS:GRAYSCALE=Niveaux de gris
        '''FILTERS:NEGATIVE=Négatif
        '''FILTERS:SEPIA=Ton sépia
        '''FILTERS:BRIGHTER=Plus clair
        '''FILTERS:DARKER=Plus foncé
        '''FILTERS:INTENSIFY=Intensifier
        '''FILTERS:REDONLY=Rouge uniquement
        '''FILTERS:GREENONLY=Vert uniquement
        '''FILTERS:BLUEONLY=Bleu uniquement
        '''FILTERS:RGBSHUFFLE= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_Français() As String
            Get
                Return ResourceManager.GetString("lang_Français", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #author=Jonas Triki (Triki Technologies)
        '''#name=Norwegian
        '''#shortname=nb
        '''#contact=webmaster@triki-tech.com
        '''#site=http://triki-tech.com
        '''
        '''RGB=RGB
        '''RGB:R=R
        '''RGB:G=G
        '''RGB:B=B
        '''
        '''HSV=HSV
        '''HSV:H=H
        '''HSV:S=S
        '''HSV:V=V
        '''
        '''FILTERS=Filtere
        '''FILTERS:GRAYSCALE=Gråtone
        '''FILTERS:NEGATIVE=Negativt
        '''FILTERS:SEPIA=Sepia
        '''FILTERS:BRIGHTER=Lysere
        '''FILTERS:DARKER=Mørkere
        '''FILTERS:INTENSIFY=Forsterking
        '''FILTERS:REDONLY=Bare rød
        '''FILTERS:GREENONLY=Bare grønn
        '''FILTERS:BLUEONLY=Bare blå
        '''FILTERS:RGBSHUFFLE=RGB Miks
        '''FILTERS:HOVER=Dra markøren over et filt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_Norwegian() As String
            Get
                Return ResourceManager.GetString("lang_Norwegian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #author=Xylem Studios
        '''#name=Spanish
        '''#shortname=es
        '''#contact=webmaster@xylemstudios.com
        '''#site=http://xylemstudios.com
        '''
        '''RGB=RGB
        '''RGB:R=R
        '''RGB:G=G
        '''RGB:B=B
        '''
        '''HSV=HSV
        '''HSV:H=H
        '''HSV:S=S
        '''HSV:V=V
        '''
        '''FILTERS=Filtros
        '''FILTERS:GRAYSCALE=Escala de grises
        '''FILTERS:NEGATIVE=Negativo
        '''FILTERS:SEPIA=Sepia
        '''FILTERS:BRIGHTER=Más claro
        '''FILTERS:DARKER=Más oscuro
        '''FILTERS:INTENSIFY=Intensificar
        '''FILTERS:REDONLY=Sólo rojo
        '''FILTERS:GREENONLY=Sólo verde
        '''FILTERS:BLUEONLY=Sólo azúl
        '''FILTERS:RGBSHUFFLE=Mezcla RGB
        '''FILTERS:H [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lang_Spanish() As String
            Get
                Return ResourceManager.GetString("lang_Spanish", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property pipette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pipette_upsidedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pipette_upsidedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property websafecoloricon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("websafecoloricon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property websafecoloricongray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("websafecoloricongray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
